syntax = "proto3";

package scarlettcore.emissions.v1;

import "amino/amino.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "scarlettcore/emissions/v1/params.proto";

option go_package = "scarlett-core/x/emissions/types";

// Query defines the gRPC querier service.
service Query {
  
  // Parameters queries the parameters of the module.
  rpc Params (QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/scarlett-core/emissions/v1/params";
  
  }
  
  // EmissionParams Queries a list of EmissionParams items.
  rpc EmissionParams (QueryEmissionParamsRequest) returns (QueryEmissionParamsResponse) {
    option (google.api.http).get = "/scarlett-core/emissions/v1/emission_params";
  
  }
  
  // EmissionHistory Queries a list of EmissionHistory items.
  rpc EmissionHistory (QueryEmissionHistoryRequest) returns (QueryEmissionHistoryResponse) {
    option (google.api.http).get = "/scarlett-core/emissions/v1/emission_history";
  
  }
  
  // DestinationStats Queries a list of DestinationStats items.
  rpc DestinationStats (QueryDestinationStatsRequest) returns (QueryDestinationStatsResponse) {
    option (google.api.http).get = "/scarlett-core/emissions/v1/destination_stats";
  
  }
}
// QueryParamsRequest is request type for the Query/Params RPC method.
message QueryParamsRequest {}

// QueryParamsResponse is response type for the Query/Params RPC method.
message QueryParamsResponse {
  
  // params holds all the parameters of this module.
  Params params = 1 [(gogoproto.nullable) = false, (amino.dont_omitempty) = true];
}

// QueryEmissionParamsRequest defines the QueryEmissionParamsRequest message.
message QueryEmissionParamsRequest {}

// QueryEmissionParamsResponse defines the QueryEmissionParamsResponse message.
message QueryEmissionParamsResponse {}

// QueryEmissionHistoryRequest defines the QueryEmissionHistoryRequest message.
message QueryEmissionHistoryRequest {}

// QueryEmissionHistoryResponse defines the QueryEmissionHistoryResponse message.
message QueryEmissionHistoryResponse {}

// QueryDestinationStatsRequest defines the QueryDestinationStatsRequest message.
message QueryDestinationStatsRequest {}

// QueryDestinationStatsResponse defines the QueryDestinationStatsResponse message.
message QueryDestinationStatsResponse {}

