syntax = "proto3";

package scarlettcore.proofofdegen.v1;

import "amino/amino.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "scarlettcore/proofofdegen/v1/campaign.proto";
import "scarlettcore/proofofdegen/v1/eligible_wallet.proto";
import "scarlettcore/proofofdegen/v1/params.proto";

option go_package = "scarlett-core/x/proofofdegen/types";

// Query defines the gRPC querier service.
service Query {
  // Parameters queries the parameters of the module.
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/scarlett-core/proofofdegen/v1/params";
  }

  // ListCampaign Queries a list of Campaign items.
  rpc GetCampaign(QueryGetCampaignRequest) returns (QueryGetCampaignResponse) {
    option (google.api.http).get = "/scarlett-core/proofofdegen/v1/campaign/{index}";
  }

  // ListCampaign defines the ListCampaign RPC.
  rpc ListCampaign(QueryAllCampaignRequest) returns (QueryAllCampaignResponse) {
    option (google.api.http).get = "/scarlett-core/proofofdegen/v1/campaign";
  }

  // ListEligibleWallet Queries a list of EligibleWallet items.
  rpc GetEligibleWallet(QueryGetEligibleWalletRequest) returns (QueryGetEligibleWalletResponse) {
    option (google.api.http).get = "/scarlett-core/proofofdegen/v1/eligible_wallet/{index}";
  }

  // ListEligibleWallet defines the ListEligibleWallet RPC.
  rpc ListEligibleWallet(QueryAllEligibleWalletRequest) returns (QueryAllEligibleWalletResponse) {
    option (google.api.http).get = "/scarlett-core/proofofdegen/v1/eligible_wallet";
  }

  // EligibleAmount Queries a list of EligibleAmount items.
  rpc EligibleAmount(QueryEligibleAmountRequest) returns (QueryEligibleAmountResponse) {
    option (google.api.http).get = "/scarlett-core/proofofdegen/v1/eligible_amount/{address}";
  }

  // CampaignInfo Queries a list of CampaignInfo items.
  rpc CampaignInfo(QueryCampaignInfoRequest) returns (QueryCampaignInfoResponse) {
    option (google.api.http).get = "/scarlett-core/proofofdegen/v1/campaign_info";
  }
}

// QueryParamsRequest is request type for the Query/Params RPC method.
message QueryParamsRequest {}

// QueryParamsResponse is response type for the Query/Params RPC method.
message QueryParamsResponse {
  // params holds all the parameters of this module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// QueryGetCampaignRequest defines the QueryGetCampaignRequest message.
message QueryGetCampaignRequest {
  string index = 1;
}

// QueryGetCampaignResponse defines the QueryGetCampaignResponse message.
message QueryGetCampaignResponse {
  Campaign campaign = 1 [(gogoproto.nullable) = false];
}

// QueryAllCampaignRequest defines the QueryAllCampaignRequest message.
message QueryAllCampaignRequest {
  cosmos.base.query.v1beta1.PageRequest pagination = 1;
}

// QueryAllCampaignResponse defines the QueryAllCampaignResponse message.
message QueryAllCampaignResponse {
  repeated Campaign campaign = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

// QueryGetEligibleWalletRequest defines the QueryGetEligibleWalletRequest message.
message QueryGetEligibleWalletRequest {
  string index = 1;
}

// QueryGetEligibleWalletResponse defines the QueryGetEligibleWalletResponse message.
message QueryGetEligibleWalletResponse {
  EligibleWallet eligible_wallet = 1 [(gogoproto.nullable) = false];
}

// QueryAllEligibleWalletRequest defines the QueryAllEligibleWalletRequest message.
message QueryAllEligibleWalletRequest {
  cosmos.base.query.v1beta1.PageRequest pagination = 1;
}

// QueryAllEligibleWalletResponse defines the QueryAllEligibleWalletResponse message.
message QueryAllEligibleWalletResponse {
  repeated EligibleWallet eligible_wallet = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

// QueryEligibleAmountRequest defines the QueryEligibleAmountRequest message.
message QueryEligibleAmountRequest {
  string address = 1;
}

// QueryEligibleAmountResponse defines the QueryEligibleAmountResponse message.
message QueryEligibleAmountResponse {
  bool is_eligible = 1;
  uint64 claimable_amount = 2;
  string status = 3;
  uint64 wallet_weight = 4;
  uint64 total_unclaimed_wallets = 5;
  double weight_percentage = 6;
  uint64 claimed_at = 7;
}

// QueryCampaignInfoRequest defines the QueryCampaignInfoRequest message.
message QueryCampaignInfoRequest {}

// QueryCampaignInfoResponse defines the QueryCampaignInfoResponse message.
message QueryCampaignInfoResponse {
  uint64 total_emissions_received = 1;
  uint64 total_unclaimed_wallets = 2;
  uint64 total_claimed_wallets = 3;
  uint64 total_unclaimed_weight = 4;
  uint64 current_module_balance = 5;
  string campaign_status = 6;
}
