syntax = "proto3";

package scarlettcore.proofofdegen.v1;

import "amino/amino.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "scarlettcore/proofofdegen/v1/params.proto";

option go_package = "scarlett-core/x/proofofdegen/types";

// Msg defines the Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  // UpdateParams defines a (governance) operation for updating the module
  // parameters. The authority defaults to the x/gov module account.
  rpc UpdateParams(MsgUpdateParams) returns (MsgUpdateParamsResponse);

  // CreateCampaign defines the CreateCampaign RPC.
  rpc CreateCampaign(MsgCreateCampaign) returns (MsgCreateCampaignResponse);

  // UpdateCampaign defines the UpdateCampaign RPC.
  rpc UpdateCampaign(MsgUpdateCampaign) returns (MsgUpdateCampaignResponse);

  // DeleteCampaign defines the DeleteCampaign RPC.
  rpc DeleteCampaign(MsgDeleteCampaign) returns (MsgDeleteCampaignResponse);

  // CreateEligibleWallet defines the CreateEligibleWallet RPC.
  rpc CreateEligibleWallet(MsgCreateEligibleWallet) returns (MsgCreateEligibleWalletResponse);

  // UpdateEligibleWallet defines the UpdateEligibleWallet RPC.
  rpc UpdateEligibleWallet(MsgUpdateEligibleWallet) returns (MsgUpdateEligibleWalletResponse);

  // DeleteEligibleWallet defines the DeleteEligibleWallet RPC.
  rpc DeleteEligibleWallet(MsgDeleteEligibleWallet) returns (MsgDeleteEligibleWalletResponse);
}

// MsgUpdateParams is the Msg/UpdateParams request type.
message MsgUpdateParams {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "scarlettcore/x/proofofdegen/MsgUpdateParams";

  // authority is the address that controls the module (defaults to x/gov unless overwritten).
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  // params defines the module parameters to update.

  // NOTE: All parameters must be supplied.
  Params params = 2 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
message MsgUpdateParamsResponse {}

// MsgCreateCampaign defines the MsgCreateCampaign message.
message MsgCreateCampaign {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string index = 2;
  string name = 3;
  bool active = 4;
  uint64 total_allocation = 5;
}

// MsgCreateCampaignResponse defines the MsgCreateCampaignResponse message.
message MsgCreateCampaignResponse {}

// MsgUpdateCampaign defines the MsgUpdateCampaign message.
message MsgUpdateCampaign {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string index = 2;
  string name = 3;
  bool active = 4;
  uint64 total_allocation = 5;
}

// MsgUpdateCampaignResponse defines the MsgUpdateCampaignResponse message.
message MsgUpdateCampaignResponse {}

// MsgDeleteCampaign defines the MsgDeleteCampaign message.
message MsgDeleteCampaign {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string index = 2;
}

// MsgDeleteCampaignResponse defines the MsgDeleteCampaignResponse message.
message MsgDeleteCampaignResponse {}

// MsgCreateEligibleWallet defines the MsgCreateEligibleWallet message.
message MsgCreateEligibleWallet {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string index = 2;
  string address = 3;
  bool claimed = 4;
  uint64 claim_time = 5;
  uint64 weight = 6;
}

// MsgCreateEligibleWalletResponse defines the MsgCreateEligibleWalletResponse message.
message MsgCreateEligibleWalletResponse {}

// MsgUpdateEligibleWallet defines the MsgUpdateEligibleWallet message.
message MsgUpdateEligibleWallet {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string index = 2;
  string address = 3;
  bool claimed = 4;
  uint64 claim_time = 5;
  uint64 weight = 6;
}

// MsgUpdateEligibleWalletResponse defines the MsgUpdateEligibleWalletResponse message.
message MsgUpdateEligibleWalletResponse {}

// MsgDeleteEligibleWallet defines the MsgDeleteEligibleWallet message.
message MsgDeleteEligibleWallet {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string index = 2;
}

// MsgDeleteEligibleWalletResponse defines the MsgDeleteEligibleWalletResponse message.
message MsgDeleteEligibleWalletResponse {}
