package types

import "fmt"

// DefaultGenesis returns the default genesis state
func DefaultGenesis() *GenesisState {
	// Example Merkle root for testing (this would be generated by merkle-genesis-tool)
	testMerkleRoot := "example_merkle_root_hash"

	return &GenesisState{
		Params: DefaultParams(),
		CampaignMap: []Campaign{
			{
				Index:           "genesis", // Unique index for genesis campaign
				Name:            "Genesis",
				Active:          true,
				TotalAllocation: 650, // Total weight from test addresses
				MerkleRoot:      testMerkleRoot,
				ClaimedCount:    0,
				ClaimedWeight:   0,
			},
		},
		EligibleWalletMap: []EligibleWallet{}, // Empty - using Merkle proofs instead
		MerkleProofMap: []MerkleProofEntry{
			// Test Merkle proofs for testing (these would be generated by merkle-genesis-tool)
			{
				Address: "scarlett1tpsw9anauv2peeurtudrjs8rq8ngjpvc45a0zl", // Alice
				Proof: &MerkleProof{
					Proof:  []string{"test_proof_1", "test_proof_2"}, // Placeholder proofs
					Weight: 150,
				},
			},
			{
				Address: "scarlett1estg4c5xtq37xhsxtwd5gqtppnhpa7s607gt0d", // Bob
				Proof: &MerkleProof{
					Proof:  []string{"test_proof_3", "test_proof_4"}, // Placeholder proofs
					Weight: 100,
				},
			},
			{
				Address: "scarlett1v55ru2vwhrdz6jy8264dh43p43knas24tmtv45", // Validator1
				Proof: &MerkleProof{
					Proof:  []string{"test_proof_5", "test_proof_6"}, // Placeholder proofs
					Weight: 200,
				},
			},
			{
				Address: "scarlett16e8hn309ntektqcrjgznq5u0w2azt2w93e7ptc", // Validator2
				Proof: &MerkleProof{
					Proof:  []string{"test_proof_7", "test_proof_8"}, // Placeholder proofs
					Weight: 75,
				},
			},
			{
				Address: "scarlett1583vwdqgqkr3jht8pzquz988d2x52sfqrdmwu8", // Validator3
				Proof: &MerkleProof{
					Proof:  []string{"test_proof_9", "test_proof_10"}, // Placeholder proofs
					Weight: 125,
				},
			},
		},
		// this line is used by starport scaffolding # genesis/types/default
	}
}

// Validate performs basic genesis state validation returning an error upon any
// failure.
func (gs GenesisState) Validate() error {
	campaignIndexMap := make(map[string]struct{})

	for _, elem := range gs.CampaignMap {
		index := fmt.Sprint(elem.Index)
		if _, ok := campaignIndexMap[index]; ok {
			return fmt.Errorf("duplicated index for campaign")
		}
		campaignIndexMap[index] = struct{}{}
	}
	eligibleWalletIndexMap := make(map[string]struct{})

	for _, elem := range gs.EligibleWalletMap {
		index := fmt.Sprint(elem.Index)
		if _, ok := eligibleWalletIndexMap[index]; ok {
			return fmt.Errorf("duplicated index for eligibleWallet")
		}
		eligibleWalletIndexMap[index] = struct{}{}
	}

	// Validate MerkleProofMap entries
	merkleProofAddressMap := make(map[string]struct{})
	for _, elem := range gs.MerkleProofMap {
		if _, ok := merkleProofAddressMap[elem.Address]; ok {
			return fmt.Errorf("duplicated address for merkleProof: %s", elem.Address)
		}
		merkleProofAddressMap[elem.Address] = struct{}{}

		// Validate address is not empty
		if elem.Address == "" {
			return fmt.Errorf("empty address in merkleProof entry")
		}

		// Validate proof has weight > 0
		if elem.Proof != nil && elem.Proof.Weight == 0 {
			return fmt.Errorf("zero weight for address %s", elem.Address)
		}
	}

	return gs.Params.Validate()
}
