// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: scarlettcore/proofofdegen/v1/query.proto

package types

import (
	context "context"
	encoding_binary "encoding/binary"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryGetCampaignRequest defines the QueryGetCampaignRequest message.
type QueryGetCampaignRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetCampaignRequest) Reset()         { *m = QueryGetCampaignRequest{} }
func (m *QueryGetCampaignRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCampaignRequest) ProtoMessage()    {}
func (*QueryGetCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{2}
}
func (m *QueryGetCampaignRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCampaignRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCampaignRequest.Merge(m, src)
}
func (m *QueryGetCampaignRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCampaignRequest proto.InternalMessageInfo

func (m *QueryGetCampaignRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

// QueryGetCampaignResponse defines the QueryGetCampaignResponse message.
type QueryGetCampaignResponse struct {
	Campaign Campaign `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign"`
}

func (m *QueryGetCampaignResponse) Reset()         { *m = QueryGetCampaignResponse{} }
func (m *QueryGetCampaignResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCampaignResponse) ProtoMessage()    {}
func (*QueryGetCampaignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{3}
}
func (m *QueryGetCampaignResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCampaignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCampaignResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCampaignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCampaignResponse.Merge(m, src)
}
func (m *QueryGetCampaignResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCampaignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCampaignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCampaignResponse proto.InternalMessageInfo

func (m *QueryGetCampaignResponse) GetCampaign() Campaign {
	if m != nil {
		return m.Campaign
	}
	return Campaign{}
}

// QueryAllCampaignRequest defines the QueryAllCampaignRequest message.
type QueryAllCampaignRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCampaignRequest) Reset()         { *m = QueryAllCampaignRequest{} }
func (m *QueryAllCampaignRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCampaignRequest) ProtoMessage()    {}
func (*QueryAllCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{4}
}
func (m *QueryAllCampaignRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCampaignRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCampaignRequest.Merge(m, src)
}
func (m *QueryAllCampaignRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCampaignRequest proto.InternalMessageInfo

func (m *QueryAllCampaignRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllCampaignResponse defines the QueryAllCampaignResponse message.
type QueryAllCampaignResponse struct {
	Campaign   []Campaign          `protobuf:"bytes,1,rep,name=campaign,proto3" json:"campaign"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCampaignResponse) Reset()         { *m = QueryAllCampaignResponse{} }
func (m *QueryAllCampaignResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCampaignResponse) ProtoMessage()    {}
func (*QueryAllCampaignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{5}
}
func (m *QueryAllCampaignResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCampaignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCampaignResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCampaignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCampaignResponse.Merge(m, src)
}
func (m *QueryAllCampaignResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCampaignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCampaignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCampaignResponse proto.InternalMessageInfo

func (m *QueryAllCampaignResponse) GetCampaign() []Campaign {
	if m != nil {
		return m.Campaign
	}
	return nil
}

func (m *QueryAllCampaignResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryGetEligibleWalletRequest defines the QueryGetEligibleWalletRequest message.
type QueryGetEligibleWalletRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetEligibleWalletRequest) Reset()         { *m = QueryGetEligibleWalletRequest{} }
func (m *QueryGetEligibleWalletRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetEligibleWalletRequest) ProtoMessage()    {}
func (*QueryGetEligibleWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{6}
}
func (m *QueryGetEligibleWalletRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEligibleWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEligibleWalletRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEligibleWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEligibleWalletRequest.Merge(m, src)
}
func (m *QueryGetEligibleWalletRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEligibleWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEligibleWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEligibleWalletRequest proto.InternalMessageInfo

func (m *QueryGetEligibleWalletRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

// QueryGetEligibleWalletResponse defines the QueryGetEligibleWalletResponse message.
type QueryGetEligibleWalletResponse struct {
	EligibleWallet EligibleWallet `protobuf:"bytes,1,opt,name=eligible_wallet,json=eligibleWallet,proto3" json:"eligible_wallet"`
}

func (m *QueryGetEligibleWalletResponse) Reset()         { *m = QueryGetEligibleWalletResponse{} }
func (m *QueryGetEligibleWalletResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetEligibleWalletResponse) ProtoMessage()    {}
func (*QueryGetEligibleWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{7}
}
func (m *QueryGetEligibleWalletResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEligibleWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEligibleWalletResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEligibleWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEligibleWalletResponse.Merge(m, src)
}
func (m *QueryGetEligibleWalletResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEligibleWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEligibleWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEligibleWalletResponse proto.InternalMessageInfo

func (m *QueryGetEligibleWalletResponse) GetEligibleWallet() EligibleWallet {
	if m != nil {
		return m.EligibleWallet
	}
	return EligibleWallet{}
}

// QueryAllEligibleWalletRequest defines the QueryAllEligibleWalletRequest message.
type QueryAllEligibleWalletRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllEligibleWalletRequest) Reset()         { *m = QueryAllEligibleWalletRequest{} }
func (m *QueryAllEligibleWalletRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllEligibleWalletRequest) ProtoMessage()    {}
func (*QueryAllEligibleWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{8}
}
func (m *QueryAllEligibleWalletRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllEligibleWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllEligibleWalletRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllEligibleWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllEligibleWalletRequest.Merge(m, src)
}
func (m *QueryAllEligibleWalletRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllEligibleWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllEligibleWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllEligibleWalletRequest proto.InternalMessageInfo

func (m *QueryAllEligibleWalletRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllEligibleWalletResponse defines the QueryAllEligibleWalletResponse message.
type QueryAllEligibleWalletResponse struct {
	EligibleWallet []EligibleWallet    `protobuf:"bytes,1,rep,name=eligible_wallet,json=eligibleWallet,proto3" json:"eligible_wallet"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllEligibleWalletResponse) Reset()         { *m = QueryAllEligibleWalletResponse{} }
func (m *QueryAllEligibleWalletResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllEligibleWalletResponse) ProtoMessage()    {}
func (*QueryAllEligibleWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{9}
}
func (m *QueryAllEligibleWalletResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllEligibleWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllEligibleWalletResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllEligibleWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllEligibleWalletResponse.Merge(m, src)
}
func (m *QueryAllEligibleWalletResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllEligibleWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllEligibleWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllEligibleWalletResponse proto.InternalMessageInfo

func (m *QueryAllEligibleWalletResponse) GetEligibleWallet() []EligibleWallet {
	if m != nil {
		return m.EligibleWallet
	}
	return nil
}

func (m *QueryAllEligibleWalletResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryEligibleAmountRequest defines the QueryEligibleAmountRequest message.
type QueryEligibleAmountRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryEligibleAmountRequest) Reset()         { *m = QueryEligibleAmountRequest{} }
func (m *QueryEligibleAmountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEligibleAmountRequest) ProtoMessage()    {}
func (*QueryEligibleAmountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{10}
}
func (m *QueryEligibleAmountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEligibleAmountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEligibleAmountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEligibleAmountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEligibleAmountRequest.Merge(m, src)
}
func (m *QueryEligibleAmountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEligibleAmountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEligibleAmountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEligibleAmountRequest proto.InternalMessageInfo

func (m *QueryEligibleAmountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryEligibleAmountResponse defines the QueryEligibleAmountResponse message.
type QueryEligibleAmountResponse struct {
	IsEligible            bool    `protobuf:"varint,1,opt,name=is_eligible,json=isEligible,proto3" json:"is_eligible,omitempty"`
	ClaimableAmount       uint64  `protobuf:"varint,2,opt,name=claimable_amount,json=claimableAmount,proto3" json:"claimable_amount,omitempty"`
	Status                string  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	WalletWeight          uint64  `protobuf:"varint,4,opt,name=wallet_weight,json=walletWeight,proto3" json:"wallet_weight,omitempty"`
	TotalUnclaimedWallets uint64  `protobuf:"varint,5,opt,name=total_unclaimed_wallets,json=totalUnclaimedWallets,proto3" json:"total_unclaimed_wallets,omitempty"`
	WeightPercentage      float64 `protobuf:"fixed64,6,opt,name=weight_percentage,json=weightPercentage,proto3" json:"weight_percentage,omitempty"`
	ClaimedAt             uint64  `protobuf:"varint,7,opt,name=claimed_at,json=claimedAt,proto3" json:"claimed_at,omitempty"`
}

func (m *QueryEligibleAmountResponse) Reset()         { *m = QueryEligibleAmountResponse{} }
func (m *QueryEligibleAmountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEligibleAmountResponse) ProtoMessage()    {}
func (*QueryEligibleAmountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{11}
}
func (m *QueryEligibleAmountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEligibleAmountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEligibleAmountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEligibleAmountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEligibleAmountResponse.Merge(m, src)
}
func (m *QueryEligibleAmountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEligibleAmountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEligibleAmountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEligibleAmountResponse proto.InternalMessageInfo

func (m *QueryEligibleAmountResponse) GetIsEligible() bool {
	if m != nil {
		return m.IsEligible
	}
	return false
}

func (m *QueryEligibleAmountResponse) GetClaimableAmount() uint64 {
	if m != nil {
		return m.ClaimableAmount
	}
	return 0
}

func (m *QueryEligibleAmountResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *QueryEligibleAmountResponse) GetWalletWeight() uint64 {
	if m != nil {
		return m.WalletWeight
	}
	return 0
}

func (m *QueryEligibleAmountResponse) GetTotalUnclaimedWallets() uint64 {
	if m != nil {
		return m.TotalUnclaimedWallets
	}
	return 0
}

func (m *QueryEligibleAmountResponse) GetWeightPercentage() float64 {
	if m != nil {
		return m.WeightPercentage
	}
	return 0
}

func (m *QueryEligibleAmountResponse) GetClaimedAt() uint64 {
	if m != nil {
		return m.ClaimedAt
	}
	return 0
}

// QueryCampaignInfoRequest defines the QueryCampaignInfoRequest message.
type QueryCampaignInfoRequest struct {
}

func (m *QueryCampaignInfoRequest) Reset()         { *m = QueryCampaignInfoRequest{} }
func (m *QueryCampaignInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCampaignInfoRequest) ProtoMessage()    {}
func (*QueryCampaignInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{12}
}
func (m *QueryCampaignInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCampaignInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCampaignInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCampaignInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCampaignInfoRequest.Merge(m, src)
}
func (m *QueryCampaignInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCampaignInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCampaignInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCampaignInfoRequest proto.InternalMessageInfo

// QueryCampaignInfoResponse defines the QueryCampaignInfoResponse message.
type QueryCampaignInfoResponse struct {
	TotalEmissionsReceived uint64 `protobuf:"varint,1,opt,name=total_emissions_received,json=totalEmissionsReceived,proto3" json:"total_emissions_received,omitempty"`
	TotalUnclaimedWallets  uint64 `protobuf:"varint,2,opt,name=total_unclaimed_wallets,json=totalUnclaimedWallets,proto3" json:"total_unclaimed_wallets,omitempty"`
	TotalClaimedWallets    uint64 `protobuf:"varint,3,opt,name=total_claimed_wallets,json=totalClaimedWallets,proto3" json:"total_claimed_wallets,omitempty"`
	TotalUnclaimedWeight   uint64 `protobuf:"varint,4,opt,name=total_unclaimed_weight,json=totalUnclaimedWeight,proto3" json:"total_unclaimed_weight,omitempty"`
	CurrentModuleBalance   uint64 `protobuf:"varint,5,opt,name=current_module_balance,json=currentModuleBalance,proto3" json:"current_module_balance,omitempty"`
	CampaignStatus         string `protobuf:"bytes,6,opt,name=campaign_status,json=campaignStatus,proto3" json:"campaign_status,omitempty"`
}

func (m *QueryCampaignInfoResponse) Reset()         { *m = QueryCampaignInfoResponse{} }
func (m *QueryCampaignInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCampaignInfoResponse) ProtoMessage()    {}
func (*QueryCampaignInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2a2b66ad200e2d0, []int{13}
}
func (m *QueryCampaignInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCampaignInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCampaignInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCampaignInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCampaignInfoResponse.Merge(m, src)
}
func (m *QueryCampaignInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCampaignInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCampaignInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCampaignInfoResponse proto.InternalMessageInfo

func (m *QueryCampaignInfoResponse) GetTotalEmissionsReceived() uint64 {
	if m != nil {
		return m.TotalEmissionsReceived
	}
	return 0
}

func (m *QueryCampaignInfoResponse) GetTotalUnclaimedWallets() uint64 {
	if m != nil {
		return m.TotalUnclaimedWallets
	}
	return 0
}

func (m *QueryCampaignInfoResponse) GetTotalClaimedWallets() uint64 {
	if m != nil {
		return m.TotalClaimedWallets
	}
	return 0
}

func (m *QueryCampaignInfoResponse) GetTotalUnclaimedWeight() uint64 {
	if m != nil {
		return m.TotalUnclaimedWeight
	}
	return 0
}

func (m *QueryCampaignInfoResponse) GetCurrentModuleBalance() uint64 {
	if m != nil {
		return m.CurrentModuleBalance
	}
	return 0
}

func (m *QueryCampaignInfoResponse) GetCampaignStatus() string {
	if m != nil {
		return m.CampaignStatus
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "scarlettcore.proofofdegen.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "scarlettcore.proofofdegen.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetCampaignRequest)(nil), "scarlettcore.proofofdegen.v1.QueryGetCampaignRequest")
	proto.RegisterType((*QueryGetCampaignResponse)(nil), "scarlettcore.proofofdegen.v1.QueryGetCampaignResponse")
	proto.RegisterType((*QueryAllCampaignRequest)(nil), "scarlettcore.proofofdegen.v1.QueryAllCampaignRequest")
	proto.RegisterType((*QueryAllCampaignResponse)(nil), "scarlettcore.proofofdegen.v1.QueryAllCampaignResponse")
	proto.RegisterType((*QueryGetEligibleWalletRequest)(nil), "scarlettcore.proofofdegen.v1.QueryGetEligibleWalletRequest")
	proto.RegisterType((*QueryGetEligibleWalletResponse)(nil), "scarlettcore.proofofdegen.v1.QueryGetEligibleWalletResponse")
	proto.RegisterType((*QueryAllEligibleWalletRequest)(nil), "scarlettcore.proofofdegen.v1.QueryAllEligibleWalletRequest")
	proto.RegisterType((*QueryAllEligibleWalletResponse)(nil), "scarlettcore.proofofdegen.v1.QueryAllEligibleWalletResponse")
	proto.RegisterType((*QueryEligibleAmountRequest)(nil), "scarlettcore.proofofdegen.v1.QueryEligibleAmountRequest")
	proto.RegisterType((*QueryEligibleAmountResponse)(nil), "scarlettcore.proofofdegen.v1.QueryEligibleAmountResponse")
	proto.RegisterType((*QueryCampaignInfoRequest)(nil), "scarlettcore.proofofdegen.v1.QueryCampaignInfoRequest")
	proto.RegisterType((*QueryCampaignInfoResponse)(nil), "scarlettcore.proofofdegen.v1.QueryCampaignInfoResponse")
}

func init() {
	proto.RegisterFile("scarlettcore/proofofdegen/v1/query.proto", fileDescriptor_d2a2b66ad200e2d0)
}

var fileDescriptor_d2a2b66ad200e2d0 = []byte{
	// 1032 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xcf, 0x39, 0x89, 0xdb, 0x4c, 0x42, 0xd2, 0x6c, 0x4d, 0x6a, 0x4c, 0xeb, 0x56, 0xc7, 0x9f,
	0x24, 0xfd, 0x73, 0x57, 0x87, 0xd4, 0x0d, 0x50, 0x21, 0x92, 0xaa, 0x04, 0x24, 0x90, 0xc2, 0x21,
	0x54, 0x09, 0x24, 0x4e, 0x6b, 0x7b, 0x73, 0x9c, 0x74, 0xbe, 0x75, 0x6f, 0xd7, 0x69, 0xab, 0x2a,
	0x2f, 0x7c, 0x02, 0x24, 0x5e, 0xf9, 0x00, 0x08, 0x01, 0xe2, 0x85, 0xaf, 0x00, 0x7d, 0x42, 0x95,
	0x90, 0x10, 0x4f, 0x08, 0x25, 0x48, 0x7c, 0x0d, 0xe4, 0xdd, 0x39, 0xd7, 0x67, 0x5f, 0x2e, 0xe7,
	0x28, 0x2f, 0x91, 0x6f, 0x66, 0x7f, 0x33, 0xbf, 0xdf, 0xcc, 0xec, 0x8e, 0x02, 0x2b, 0xa2, 0x49,
	0xa3, 0x80, 0x49, 0xd9, 0xe4, 0x11, 0xb3, 0x3b, 0x11, 0xe7, 0xbb, 0x7c, 0xb7, 0xc5, 0x3c, 0x16,
	0xda, 0x7b, 0x35, 0xfb, 0x41, 0x97, 0x45, 0x8f, 0xad, 0x4e, 0xc4, 0x25, 0x27, 0x17, 0x07, 0x4f,
	0x5a, 0x83, 0x27, 0xad, 0xbd, 0x5a, 0x65, 0x91, 0xb6, 0xfd, 0x90, 0xdb, 0xea, 0xaf, 0x06, 0x54,
	0xae, 0x36, 0xb9, 0x68, 0x73, 0x61, 0x37, 0xa8, 0x60, 0x3a, 0x92, 0xbd, 0x57, 0x6b, 0x30, 0x49,
	0x6b, 0x76, 0x87, 0x7a, 0x7e, 0x48, 0xa5, 0xcf, 0x43, 0x3c, 0x5b, 0xf2, 0xb8, 0xc7, 0xd5, 0x4f,
	0xbb, 0xf7, 0x0b, 0xad, 0x17, 0x3d, 0xce, 0xbd, 0x80, 0xd9, 0xb4, 0xe3, 0xdb, 0x34, 0x0c, 0xb9,
	0x54, 0x10, 0x81, 0xde, 0x6b, 0x99, 0xd4, 0x9b, 0xb4, 0xdd, 0xa1, 0xbe, 0x17, 0x27, 0x58, 0xcb,
	0x3c, 0xcc, 0x02, 0xdf, 0xf3, 0x1b, 0x01, 0x73, 0x1f, 0xd2, 0x20, 0x60, 0x12, 0x31, 0xab, 0x99,
	0x98, 0x0e, 0x8d, 0x68, 0x1b, 0xb9, 0x98, 0x25, 0x20, 0x1f, 0xf7, 0x14, 0xee, 0x28, 0xa3, 0xc3,
	0x1e, 0x74, 0x99, 0x90, 0xe6, 0x17, 0x70, 0x3e, 0x61, 0x15, 0x1d, 0x1e, 0x0a, 0x46, 0xb6, 0xa1,
	0xa8, 0xc1, 0x65, 0xe3, 0x8a, 0xb1, 0x32, 0xbb, 0xf6, 0xaa, 0x95, 0x55, 0x5a, 0x4b, 0xa3, 0xb7,
	0x66, 0x9e, 0xfe, 0x7d, 0x79, 0xe2, 0xbb, 0xff, 0x7e, 0xbe, 0x6a, 0x38, 0x08, 0x37, 0x6d, 0xb8,
	0xa0, 0xe2, 0x6f, 0x33, 0x79, 0x17, 0xe5, 0x62, 0x6a, 0x52, 0x82, 0x69, 0x3f, 0x6c, 0xb1, 0x47,
	0x2a, 0xc5, 0x8c, 0xa3, 0x3f, 0xcc, 0x16, 0x94, 0x47, 0x01, 0xc8, 0xea, 0x7d, 0x38, 0x1b, 0xd7,
	0x0c, 0x79, 0xbd, 0x9e, 0xcd, 0x2b, 0x8e, 0xb0, 0x35, 0xd5, 0x63, 0xe6, 0xf4, 0xd1, 0x26, 0x45,
	0x5a, 0x9b, 0x41, 0x30, 0x4c, 0xeb, 0x3d, 0x80, 0xe7, 0xbd, 0xef, 0xa7, 0xd1, 0x83, 0x62, 0xf5,
	0x06, 0xc5, 0xd2, 0x23, 0x87, 0x83, 0x62, 0xed, 0x50, 0x8f, 0x21, 0xd6, 0x19, 0x40, 0x9a, 0x3f,
	0x1a, 0xa8, 0x24, 0x91, 0x23, 0x55, 0xc9, 0xe4, 0xc9, 0x95, 0x90, 0xed, 0x04, 0xdd, 0x82, 0xa2,
	0xbb, 0x7c, 0x2c, 0x5d, 0x4d, 0x23, 0xc1, 0xf7, 0x16, 0x5c, 0x8a, 0x0b, 0x7f, 0x0f, 0x67, 0xed,
	0xbe, 0x1a, 0xb5, 0xec, 0x7e, 0xed, 0x43, 0xf5, 0x28, 0x18, 0x6a, 0xfd, 0x1c, 0x16, 0x86, 0x86,
	0x17, 0xab, 0x7a, 0x3d, 0x5b, 0x72, 0x32, 0x1c, 0x0a, 0x9f, 0x67, 0x09, 0xab, 0xe9, 0x21, 0xeb,
	0xcd, 0x20, 0x48, 0x67, 0x7d, 0x5a, 0xed, 0xfc, 0xd5, 0x40, 0xa1, 0x29, 0x99, 0xb2, 0x84, 0x4e,
	0x9e, 0x8e, 0xd0, 0xd3, 0xeb, 0x73, 0x1d, 0x2a, 0x4a, 0x47, 0x9c, 0x75, 0xb3, 0xcd, 0xbb, 0x61,
	0xbf, 0x5c, 0x65, 0x38, 0x43, 0x5b, 0xad, 0x88, 0x09, 0x81, 0x6d, 0x8e, 0x3f, 0xcd, 0xef, 0x0b,
	0xf0, 0x72, 0x2a, 0x10, 0xd5, 0x5f, 0x86, 0x59, 0x5f, 0xb8, 0x31, 0x6b, 0x85, 0x3e, 0xeb, 0x80,
	0x2f, 0xe2, 0xe3, 0x64, 0x15, 0xce, 0x35, 0x03, 0xea, 0xb7, 0x69, 0xaf, 0x3e, 0x54, 0x81, 0x95,
	0x8e, 0x29, 0x67, 0xa1, 0x6f, 0xd7, 0x31, 0xc9, 0x12, 0x14, 0x85, 0xa4, 0xb2, 0x2b, 0xca, 0x93,
	0x8a, 0x04, 0x7e, 0x91, 0x57, 0xe0, 0x05, 0x5d, 0x58, 0xf7, 0x21, 0xf3, 0xbd, 0x2f, 0x65, 0x79,
	0x4a, 0xe1, 0xe7, 0xb4, 0xf1, 0xbe, 0xb2, 0x91, 0x3a, 0x5c, 0x90, 0x5c, 0xd2, 0xc0, 0xed, 0x86,
	0x2a, 0x2e, 0x6b, 0x61, 0x37, 0x44, 0x79, 0x5a, 0x1d, 0x7f, 0x51, 0xb9, 0x3f, 0x8d, 0xbd, 0xba,
	0xc0, 0x82, 0x5c, 0x83, 0x45, 0x1d, 0xd5, 0xed, 0xb0, 0xa8, 0xc9, 0x42, 0x49, 0x3d, 0x56, 0x2e,
	0x5e, 0x31, 0x56, 0x0c, 0xe7, 0x9c, 0x76, 0xec, 0xf4, 0xed, 0xe4, 0x12, 0x40, 0x1c, 0x9c, 0xca,
	0xf2, 0x19, 0x15, 0x77, 0x06, 0x2d, 0x9b, 0xd2, 0xac, 0xe0, 0xdd, 0x8f, 0xaf, 0xed, 0x07, 0xe1,
	0x2e, 0x8f, 0x9f, 0xdc, 0x3f, 0x0b, 0xf0, 0x52, 0x8a, 0x13, 0xcb, 0xb8, 0x01, 0x65, 0xcd, 0x9e,
	0xb5, 0x7d, 0x21, 0x7a, 0xbb, 0xc4, 0x8d, 0x58, 0x93, 0xf9, 0x7b, 0xac, 0xa5, 0x6a, 0x3a, 0xe5,
	0x2c, 0x29, 0xff, 0xbd, 0xd8, 0xed, 0xa0, 0x37, 0x4b, 0x77, 0x21, 0x4b, 0xf7, 0x1a, 0x68, 0x87,
	0x3b, 0x8c, 0x9a, 0x54, 0xa8, 0xf3, 0xca, 0x79, 0x37, 0x89, 0x59, 0x87, 0xa5, 0x91, 0x5c, 0x83,
	0x1d, 0x29, 0x0d, 0xa5, 0xd2, 0x9d, 0x59, 0x87, 0xa5, 0x66, 0x37, 0x8a, 0x58, 0x28, 0xdd, 0x36,
	0x6f, 0x75, 0x03, 0xe6, 0x36, 0x68, 0x40, 0xc3, 0x26, 0xc3, 0xc6, 0x94, 0xd0, 0xfb, 0x91, 0x72,
	0x6e, 0x69, 0x1f, 0x59, 0x86, 0x85, 0xf8, 0xb5, 0x73, 0x71, 0x2a, 0x8a, 0x6a, 0x2a, 0xe6, 0x63,
	0xf3, 0x27, 0xca, 0xba, 0xf6, 0x03, 0xc0, 0xb4, 0x2a, 0x2c, 0xf9, 0xd6, 0x80, 0xa2, 0xde, 0x49,
	0xe4, 0x66, 0xf6, 0xdd, 0x1b, 0x5d, 0x89, 0x95, 0xda, 0x18, 0x08, 0xdd, 0x34, 0xf3, 0xc6, 0x57,
	0x7f, 0xfc, 0xfb, 0x4d, 0x61, 0x99, 0xbc, 0x66, 0xc7, 0xd0, 0x1b, 0x19, 0x0b, 0x99, 0xfc, 0x62,
	0xc0, 0xec, 0xc0, 0x7e, 0x23, 0xb7, 0x72, 0x64, 0x1c, 0x5d, 0xa0, 0x95, 0xfa, 0xb8, 0x30, 0x64,
	0x7b, 0x5b, 0xb1, 0xad, 0x11, 0xfb, 0x18, 0xb6, 0x71, 0x79, 0xed, 0x27, 0xea, 0xa9, 0xdf, 0x27,
	0x3f, 0x19, 0x30, 0xf7, 0xa1, 0x2f, 0xc6, 0x23, 0x3e, 0xba, 0x62, 0x73, 0x11, 0x4f, 0xd9, 0x9a,
	0xa6, 0xad, 0x88, 0xaf, 0x92, 0xe5, 0x9c, 0xc4, 0xc9, 0xef, 0x06, 0x2c, 0x8e, 0x2c, 0x26, 0xf2,
	0x76, 0xbe, 0xba, 0xa5, 0xee, 0x93, 0xca, 0x9d, 0x93, 0x81, 0x51, 0xc1, 0x3b, 0x4a, 0xc1, 0x06,
	0xa9, 0x1f, 0xa3, 0x60, 0x68, 0x8f, 0xf4, 0x3b, 0xf0, 0x9b, 0x01, 0xa4, 0xd7, 0x81, 0x13, 0x28,
	0x3a, 0x6a, 0x43, 0xe6, 0x52, 0x74, 0xe4, 0xd2, 0x33, 0xeb, 0x4a, 0xd1, 0x4d, 0x62, 0x8d, 0xa7,
	0xa8, 0xa7, 0x64, 0x3e, 0xb9, 0x49, 0xc8, 0x46, 0x0e, 0x22, 0xa9, 0x5b, 0xab, 0xf2, 0xe6, 0x09,
	0x90, 0xc8, 0xff, 0x5d, 0xc5, 0xff, 0x2d, 0xb2, 0x91, 0x97, 0xbf, 0xde, 0x5c, 0xf6, 0x13, 0xdc,
	0x8b, 0xfb, 0xbd, 0xdb, 0x3c, 0x37, 0xf8, 0x94, 0x93, 0x3c, 0xe3, 0x9d, 0xb2, 0x18, 0x2a, 0xb7,
	0xc7, 0xc6, 0xa1, 0x86, 0x75, 0xa5, 0xc1, 0x22, 0xd7, 0x73, 0xde, 0x0b, 0xd7, 0x0f, 0x77, 0xf9,
	0xd6, 0x9d, 0xa7, 0x07, 0x55, 0xe3, 0xd9, 0x41, 0xd5, 0xf8, 0xe7, 0xa0, 0x6a, 0x7c, 0x7d, 0x58,
	0x9d, 0x78, 0x76, 0x58, 0x9d, 0xf8, 0xeb, 0xb0, 0x3a, 0xf1, 0x99, 0x99, 0x0c, 0xf3, 0x28, 0x19,
	0x48, 0x3e, 0xee, 0x30, 0xd1, 0x28, 0xaa, 0xff, 0x2a, 0xde, 0xf8, 0x3f, 0x00, 0x00, 0xff, 0xff,
	0xbd, 0xa5, 0xc7, 0xfc, 0x9e, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ListCampaign Queries a list of Campaign items.
	GetCampaign(ctx context.Context, in *QueryGetCampaignRequest, opts ...grpc.CallOption) (*QueryGetCampaignResponse, error)
	// ListCampaign defines the ListCampaign RPC.
	ListCampaign(ctx context.Context, in *QueryAllCampaignRequest, opts ...grpc.CallOption) (*QueryAllCampaignResponse, error)
	// ListEligibleWallet Queries a list of EligibleWallet items.
	GetEligibleWallet(ctx context.Context, in *QueryGetEligibleWalletRequest, opts ...grpc.CallOption) (*QueryGetEligibleWalletResponse, error)
	// ListEligibleWallet defines the ListEligibleWallet RPC.
	ListEligibleWallet(ctx context.Context, in *QueryAllEligibleWalletRequest, opts ...grpc.CallOption) (*QueryAllEligibleWalletResponse, error)
	// EligibleAmount Queries a list of EligibleAmount items.
	EligibleAmount(ctx context.Context, in *QueryEligibleAmountRequest, opts ...grpc.CallOption) (*QueryEligibleAmountResponse, error)
	// CampaignInfo Queries a list of CampaignInfo items.
	CampaignInfo(ctx context.Context, in *QueryCampaignInfoRequest, opts ...grpc.CallOption) (*QueryCampaignInfoResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.proofofdegen.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetCampaign(ctx context.Context, in *QueryGetCampaignRequest, opts ...grpc.CallOption) (*QueryGetCampaignResponse, error) {
	out := new(QueryGetCampaignResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.proofofdegen.v1.Query/GetCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListCampaign(ctx context.Context, in *QueryAllCampaignRequest, opts ...grpc.CallOption) (*QueryAllCampaignResponse, error) {
	out := new(QueryAllCampaignResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.proofofdegen.v1.Query/ListCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetEligibleWallet(ctx context.Context, in *QueryGetEligibleWalletRequest, opts ...grpc.CallOption) (*QueryGetEligibleWalletResponse, error) {
	out := new(QueryGetEligibleWalletResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.proofofdegen.v1.Query/GetEligibleWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListEligibleWallet(ctx context.Context, in *QueryAllEligibleWalletRequest, opts ...grpc.CallOption) (*QueryAllEligibleWalletResponse, error) {
	out := new(QueryAllEligibleWalletResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.proofofdegen.v1.Query/ListEligibleWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EligibleAmount(ctx context.Context, in *QueryEligibleAmountRequest, opts ...grpc.CallOption) (*QueryEligibleAmountResponse, error) {
	out := new(QueryEligibleAmountResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.proofofdegen.v1.Query/EligibleAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CampaignInfo(ctx context.Context, in *QueryCampaignInfoRequest, opts ...grpc.CallOption) (*QueryCampaignInfoResponse, error) {
	out := new(QueryCampaignInfoResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.proofofdegen.v1.Query/CampaignInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ListCampaign Queries a list of Campaign items.
	GetCampaign(context.Context, *QueryGetCampaignRequest) (*QueryGetCampaignResponse, error)
	// ListCampaign defines the ListCampaign RPC.
	ListCampaign(context.Context, *QueryAllCampaignRequest) (*QueryAllCampaignResponse, error)
	// ListEligibleWallet Queries a list of EligibleWallet items.
	GetEligibleWallet(context.Context, *QueryGetEligibleWalletRequest) (*QueryGetEligibleWalletResponse, error)
	// ListEligibleWallet defines the ListEligibleWallet RPC.
	ListEligibleWallet(context.Context, *QueryAllEligibleWalletRequest) (*QueryAllEligibleWalletResponse, error)
	// EligibleAmount Queries a list of EligibleAmount items.
	EligibleAmount(context.Context, *QueryEligibleAmountRequest) (*QueryEligibleAmountResponse, error)
	// CampaignInfo Queries a list of CampaignInfo items.
	CampaignInfo(context.Context, *QueryCampaignInfoRequest) (*QueryCampaignInfoResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetCampaign(ctx context.Context, req *QueryGetCampaignRequest) (*QueryGetCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampaign not implemented")
}
func (*UnimplementedQueryServer) ListCampaign(ctx context.Context, req *QueryAllCampaignRequest) (*QueryAllCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCampaign not implemented")
}
func (*UnimplementedQueryServer) GetEligibleWallet(ctx context.Context, req *QueryGetEligibleWalletRequest) (*QueryGetEligibleWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEligibleWallet not implemented")
}
func (*UnimplementedQueryServer) ListEligibleWallet(ctx context.Context, req *QueryAllEligibleWalletRequest) (*QueryAllEligibleWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEligibleWallet not implemented")
}
func (*UnimplementedQueryServer) EligibleAmount(ctx context.Context, req *QueryEligibleAmountRequest) (*QueryEligibleAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EligibleAmount not implemented")
}
func (*UnimplementedQueryServer) CampaignInfo(ctx context.Context, req *QueryCampaignInfoRequest) (*QueryCampaignInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CampaignInfo not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.proofofdegen.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.proofofdegen.v1.Query/GetCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetCampaign(ctx, req.(*QueryGetCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.proofofdegen.v1.Query/ListCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListCampaign(ctx, req.(*QueryAllCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetEligibleWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEligibleWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetEligibleWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.proofofdegen.v1.Query/GetEligibleWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetEligibleWallet(ctx, req.(*QueryGetEligibleWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListEligibleWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllEligibleWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListEligibleWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.proofofdegen.v1.Query/ListEligibleWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListEligibleWallet(ctx, req.(*QueryAllEligibleWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EligibleAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEligibleAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EligibleAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.proofofdegen.v1.Query/EligibleAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EligibleAmount(ctx, req.(*QueryEligibleAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CampaignInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCampaignInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CampaignInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.proofofdegen.v1.Query/CampaignInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CampaignInfo(ctx, req.(*QueryCampaignInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scarlettcore.proofofdegen.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetCampaign",
			Handler:    _Query_GetCampaign_Handler,
		},
		{
			MethodName: "ListCampaign",
			Handler:    _Query_ListCampaign_Handler,
		},
		{
			MethodName: "GetEligibleWallet",
			Handler:    _Query_GetEligibleWallet_Handler,
		},
		{
			MethodName: "ListEligibleWallet",
			Handler:    _Query_ListEligibleWallet_Handler,
		},
		{
			MethodName: "EligibleAmount",
			Handler:    _Query_EligibleAmount_Handler,
		},
		{
			MethodName: "CampaignInfo",
			Handler:    _Query_CampaignInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scarlettcore/proofofdegen/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetCampaignRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCampaignRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCampaignRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCampaignResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCampaignResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCampaignResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Campaign.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllCampaignRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCampaignRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCampaignRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCampaignResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCampaignResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCampaignResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Campaign) > 0 {
		for iNdEx := len(m.Campaign) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Campaign[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetEligibleWalletRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEligibleWalletRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEligibleWalletRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetEligibleWalletResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEligibleWalletResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEligibleWalletResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.EligibleWallet.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllEligibleWalletRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllEligibleWalletRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllEligibleWalletRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllEligibleWalletResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllEligibleWalletResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllEligibleWalletResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.EligibleWallet) > 0 {
		for iNdEx := len(m.EligibleWallet) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EligibleWallet[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryEligibleAmountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEligibleAmountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEligibleAmountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEligibleAmountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEligibleAmountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEligibleAmountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ClaimedAt != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ClaimedAt))
		i--
		dAtA[i] = 0x38
	}
	if m.WeightPercentage != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.WeightPercentage))))
		i--
		dAtA[i] = 0x31
	}
	if m.TotalUnclaimedWallets != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalUnclaimedWallets))
		i--
		dAtA[i] = 0x28
	}
	if m.WalletWeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.WalletWeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ClaimableAmount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ClaimableAmount))
		i--
		dAtA[i] = 0x10
	}
	if m.IsEligible {
		i--
		if m.IsEligible {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryCampaignInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCampaignInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCampaignInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryCampaignInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCampaignInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCampaignInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CampaignStatus) > 0 {
		i -= len(m.CampaignStatus)
		copy(dAtA[i:], m.CampaignStatus)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CampaignStatus)))
		i--
		dAtA[i] = 0x32
	}
	if m.CurrentModuleBalance != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CurrentModuleBalance))
		i--
		dAtA[i] = 0x28
	}
	if m.TotalUnclaimedWeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalUnclaimedWeight))
		i--
		dAtA[i] = 0x20
	}
	if m.TotalClaimedWallets != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalClaimedWallets))
		i--
		dAtA[i] = 0x18
	}
	if m.TotalUnclaimedWallets != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalUnclaimedWallets))
		i--
		dAtA[i] = 0x10
	}
	if m.TotalEmissionsReceived != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalEmissionsReceived))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetCampaignRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCampaignResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Campaign.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllCampaignRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCampaignResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Campaign) > 0 {
		for _, e := range m.Campaign {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetEligibleWalletRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetEligibleWalletResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.EligibleWallet.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllEligibleWalletRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllEligibleWalletResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.EligibleWallet) > 0 {
		for _, e := range m.EligibleWallet {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEligibleAmountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEligibleAmountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsEligible {
		n += 2
	}
	if m.ClaimableAmount != 0 {
		n += 1 + sovQuery(uint64(m.ClaimableAmount))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.WalletWeight != 0 {
		n += 1 + sovQuery(uint64(m.WalletWeight))
	}
	if m.TotalUnclaimedWallets != 0 {
		n += 1 + sovQuery(uint64(m.TotalUnclaimedWallets))
	}
	if m.WeightPercentage != 0 {
		n += 9
	}
	if m.ClaimedAt != 0 {
		n += 1 + sovQuery(uint64(m.ClaimedAt))
	}
	return n
}

func (m *QueryCampaignInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryCampaignInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalEmissionsReceived != 0 {
		n += 1 + sovQuery(uint64(m.TotalEmissionsReceived))
	}
	if m.TotalUnclaimedWallets != 0 {
		n += 1 + sovQuery(uint64(m.TotalUnclaimedWallets))
	}
	if m.TotalClaimedWallets != 0 {
		n += 1 + sovQuery(uint64(m.TotalClaimedWallets))
	}
	if m.TotalUnclaimedWeight != 0 {
		n += 1 + sovQuery(uint64(m.TotalUnclaimedWeight))
	}
	if m.CurrentModuleBalance != 0 {
		n += 1 + sovQuery(uint64(m.CurrentModuleBalance))
	}
	l = len(m.CampaignStatus)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCampaignRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCampaignRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCampaignRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCampaignResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCampaignResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCampaignResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Campaign", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Campaign.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCampaignRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCampaignRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCampaignRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCampaignResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCampaignResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCampaignResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Campaign", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Campaign = append(m.Campaign, Campaign{})
			if err := m.Campaign[len(m.Campaign)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetEligibleWalletRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEligibleWalletRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEligibleWalletRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetEligibleWalletResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEligibleWalletResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEligibleWalletResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EligibleWallet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EligibleWallet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllEligibleWalletRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllEligibleWalletRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllEligibleWalletRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllEligibleWalletResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllEligibleWalletResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllEligibleWalletResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EligibleWallet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EligibleWallet = append(m.EligibleWallet, EligibleWallet{})
			if err := m.EligibleWallet[len(m.EligibleWallet)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEligibleAmountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEligibleAmountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEligibleAmountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEligibleAmountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEligibleAmountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEligibleAmountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsEligible", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsEligible = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimableAmount", wireType)
			}
			m.ClaimableAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClaimableAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletWeight", wireType)
			}
			m.WalletWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WalletWeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalUnclaimedWallets", wireType)
			}
			m.TotalUnclaimedWallets = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalUnclaimedWallets |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field WeightPercentage", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.WeightPercentage = float64(math.Float64frombits(v))
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimedAt", wireType)
			}
			m.ClaimedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClaimedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCampaignInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCampaignInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCampaignInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCampaignInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCampaignInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCampaignInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalEmissionsReceived", wireType)
			}
			m.TotalEmissionsReceived = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalEmissionsReceived |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalUnclaimedWallets", wireType)
			}
			m.TotalUnclaimedWallets = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalUnclaimedWallets |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalClaimedWallets", wireType)
			}
			m.TotalClaimedWallets = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalClaimedWallets |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalUnclaimedWeight", wireType)
			}
			m.TotalUnclaimedWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalUnclaimedWeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentModuleBalance", wireType)
			}
			m.CurrentModuleBalance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentModuleBalance |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CampaignStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
