// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: scarlettcore/emissions/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88f0ec2b1eac5e40, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88f0ec2b1eac5e40, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryEmissionParamsRequest defines the QueryEmissionParamsRequest message.
type QueryEmissionParamsRequest struct {
}

func (m *QueryEmissionParamsRequest) Reset()         { *m = QueryEmissionParamsRequest{} }
func (m *QueryEmissionParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEmissionParamsRequest) ProtoMessage()    {}
func (*QueryEmissionParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88f0ec2b1eac5e40, []int{2}
}
func (m *QueryEmissionParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmissionParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmissionParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmissionParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmissionParamsRequest.Merge(m, src)
}
func (m *QueryEmissionParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmissionParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmissionParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmissionParamsRequest proto.InternalMessageInfo

// QueryEmissionParamsResponse defines the QueryEmissionParamsResponse message.
type QueryEmissionParamsResponse struct {
}

func (m *QueryEmissionParamsResponse) Reset()         { *m = QueryEmissionParamsResponse{} }
func (m *QueryEmissionParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEmissionParamsResponse) ProtoMessage()    {}
func (*QueryEmissionParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88f0ec2b1eac5e40, []int{3}
}
func (m *QueryEmissionParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmissionParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmissionParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmissionParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmissionParamsResponse.Merge(m, src)
}
func (m *QueryEmissionParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmissionParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmissionParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmissionParamsResponse proto.InternalMessageInfo

// QueryEmissionHistoryRequest defines the QueryEmissionHistoryRequest message.
type QueryEmissionHistoryRequest struct {
}

func (m *QueryEmissionHistoryRequest) Reset()         { *m = QueryEmissionHistoryRequest{} }
func (m *QueryEmissionHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEmissionHistoryRequest) ProtoMessage()    {}
func (*QueryEmissionHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88f0ec2b1eac5e40, []int{4}
}
func (m *QueryEmissionHistoryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmissionHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmissionHistoryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmissionHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmissionHistoryRequest.Merge(m, src)
}
func (m *QueryEmissionHistoryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmissionHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmissionHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmissionHistoryRequest proto.InternalMessageInfo

// QueryEmissionHistoryResponse defines the QueryEmissionHistoryResponse message.
type QueryEmissionHistoryResponse struct {
}

func (m *QueryEmissionHistoryResponse) Reset()         { *m = QueryEmissionHistoryResponse{} }
func (m *QueryEmissionHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEmissionHistoryResponse) ProtoMessage()    {}
func (*QueryEmissionHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88f0ec2b1eac5e40, []int{5}
}
func (m *QueryEmissionHistoryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmissionHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmissionHistoryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmissionHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmissionHistoryResponse.Merge(m, src)
}
func (m *QueryEmissionHistoryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmissionHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmissionHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmissionHistoryResponse proto.InternalMessageInfo

// QueryDestinationStatsRequest defines the QueryDestinationStatsRequest message.
type QueryDestinationStatsRequest struct {
}

func (m *QueryDestinationStatsRequest) Reset()         { *m = QueryDestinationStatsRequest{} }
func (m *QueryDestinationStatsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDestinationStatsRequest) ProtoMessage()    {}
func (*QueryDestinationStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88f0ec2b1eac5e40, []int{6}
}
func (m *QueryDestinationStatsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDestinationStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDestinationStatsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDestinationStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDestinationStatsRequest.Merge(m, src)
}
func (m *QueryDestinationStatsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDestinationStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDestinationStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDestinationStatsRequest proto.InternalMessageInfo

// QueryDestinationStatsResponse defines the QueryDestinationStatsResponse message.
type QueryDestinationStatsResponse struct {
}

func (m *QueryDestinationStatsResponse) Reset()         { *m = QueryDestinationStatsResponse{} }
func (m *QueryDestinationStatsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDestinationStatsResponse) ProtoMessage()    {}
func (*QueryDestinationStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88f0ec2b1eac5e40, []int{7}
}
func (m *QueryDestinationStatsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDestinationStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDestinationStatsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDestinationStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDestinationStatsResponse.Merge(m, src)
}
func (m *QueryDestinationStatsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDestinationStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDestinationStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDestinationStatsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "scarlettcore.emissions.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "scarlettcore.emissions.v1.QueryParamsResponse")
	proto.RegisterType((*QueryEmissionParamsRequest)(nil), "scarlettcore.emissions.v1.QueryEmissionParamsRequest")
	proto.RegisterType((*QueryEmissionParamsResponse)(nil), "scarlettcore.emissions.v1.QueryEmissionParamsResponse")
	proto.RegisterType((*QueryEmissionHistoryRequest)(nil), "scarlettcore.emissions.v1.QueryEmissionHistoryRequest")
	proto.RegisterType((*QueryEmissionHistoryResponse)(nil), "scarlettcore.emissions.v1.QueryEmissionHistoryResponse")
	proto.RegisterType((*QueryDestinationStatsRequest)(nil), "scarlettcore.emissions.v1.QueryDestinationStatsRequest")
	proto.RegisterType((*QueryDestinationStatsResponse)(nil), "scarlettcore.emissions.v1.QueryDestinationStatsResponse")
}

func init() {
	proto.RegisterFile("scarlettcore/emissions/v1/query.proto", fileDescriptor_88f0ec2b1eac5e40)
}

var fileDescriptor_88f0ec2b1eac5e40 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcd, 0xae, 0xd2, 0x40,
	0x18, 0x86, 0x3b, 0x26, 0x90, 0x38, 0x26, 0xfe, 0x8c, 0x2c, 0xb4, 0x42, 0xd1, 0x46, 0x8d, 0x41,
	0xdb, 0x49, 0x41, 0xfc, 0xd9, 0x12, 0x4c, 0x5c, 0x2a, 0xee, 0x74, 0x41, 0x06, 0x9c, 0xd4, 0x26,
	0xb4, 0x53, 0x3a, 0x03, 0x91, 0xad, 0x57, 0x60, 0xc2, 0x4d, 0xb8, 0x74, 0xe1, 0xc2, 0x85, 0x17,
	0xc0, 0xca, 0x90, 0xb8, 0x71, 0x75, 0x72, 0x02, 0x27, 0x39, 0xb7, 0x71, 0xc2, 0x74, 0xca, 0xa1,
	0x40, 0xf9, 0xd9, 0x34, 0xd3, 0x79, 0xdf, 0xf7, 0xfb, 0x9e, 0x7e, 0x33, 0x29, 0x7c, 0xc4, 0xbb,
	0x24, 0xea, 0x51, 0x21, 0xba, 0x2c, 0xa2, 0x98, 0xfa, 0x1e, 0xe7, 0x1e, 0x0b, 0x38, 0x1e, 0x3a,
	0xb8, 0x3f, 0xa0, 0xd1, 0xc8, 0x0e, 0x23, 0x26, 0x18, 0xba, 0xbb, 0x6a, 0xb3, 0x97, 0x36, 0x7b,
	0xe8, 0xe8, 0xb7, 0x88, 0xef, 0x05, 0x0c, 0xcb, 0x67, 0xec, 0xd6, 0x2b, 0x5d, 0xc6, 0x7d, 0xc6,
	0x71, 0x87, 0x70, 0x1a, 0x97, 0xc1, 0x43, 0xa7, 0x43, 0x05, 0x71, 0x70, 0x48, 0x5c, 0x2f, 0x20,
	0xc2, 0x63, 0x81, 0xf2, 0x16, 0x5c, 0xe6, 0x32, 0xb9, 0xc4, 0x8b, 0x95, 0xda, 0x2d, 0xba, 0x8c,
	0xb9, 0x3d, 0x8a, 0x49, 0xe8, 0x61, 0x12, 0x04, 0x4c, 0xc8, 0x08, 0x57, 0xea, 0xe3, 0x6c, 0xe8,
	0x90, 0x44, 0xc4, 0x57, 0x3e, 0xb3, 0x00, 0xd1, 0xfb, 0x45, 0xf7, 0x77, 0x72, 0xb3, 0x45, 0xfb,
	0x03, 0xca, 0x85, 0xf9, 0x09, 0xde, 0x4e, 0xed, 0xf2, 0x90, 0x05, 0x9c, 0xa2, 0x26, 0xcc, 0xc7,
	0xe1, 0x3b, 0xe0, 0x3e, 0x78, 0x72, 0xad, 0xfa, 0xc0, 0xce, 0xfc, 0x66, 0x3b, 0x8e, 0x36, 0xae,
	0x4e, 0x4e, 0xca, 0xda, 0x8f, 0xf3, 0x9f, 0x15, 0xd0, 0x52, 0x59, 0xb3, 0x08, 0x75, 0x59, 0xfc,
	0x8d, 0xb2, 0xa7, 0x5b, 0x97, 0xe0, 0xbd, 0xad, 0x6a, 0x8c, 0xb0, 0x21, 0xbf, 0xf5, 0xb8, 0x60,
	0xd1, 0x28, 0x49, 0x1b, 0xb0, 0xb8, 0x5d, 0x56, 0xf1, 0x44, 0x6f, 0x52, 0x2e, 0xd4, 0x90, 0x3f,
	0x08, 0x22, 0x96, 0xdd, 0xcb, 0xb0, 0x94, 0xa1, 0xc7, 0x05, 0xaa, 0x7f, 0x73, 0x30, 0x27, 0x1d,
	0x68, 0x0c, 0x60, 0x3e, 0x86, 0x43, 0xd6, 0x8e, 0x39, 0x6c, 0x4e, 0x57, 0xb7, 0x0f, 0xb5, 0x2b,
	0xe8, 0xca, 0xb7, 0x7f, 0x67, 0xe3, 0x2b, 0x0f, 0x91, 0x89, 0x93, 0x9c, 0x95, 0x75, 0xaa, 0xe8,
	0x17, 0x80, 0xd7, 0xd3, 0xa3, 0x43, 0xf5, 0x7d, 0xed, 0xb6, 0x1e, 0x84, 0xfe, 0xe2, 0xd8, 0x98,
	0xa2, 0xad, 0x49, 0x5a, 0x0b, 0x3d, 0xdd, 0x45, 0x9b, 0xbc, 0xb4, 0x15, 0xf6, 0x6f, 0x00, 0x6f,
	0xac, 0x9d, 0x19, 0x3a, 0x18, 0x20, 0x7d, 0x07, 0xf4, 0x97, 0x47, 0xe7, 0x14, 0xf9, 0x73, 0x49,
	0x6e, 0xa3, 0x67, 0x07, 0x91, 0x7f, 0x51, 0x98, 0x7f, 0x00, 0xbc, 0xb9, 0x7e, 0x5d, 0xd0, 0x5e,
	0x86, 0x8c, 0x0b, 0xa8, 0xbf, 0x3a, 0x3e, 0xa8, 0xe8, 0xeb, 0x92, 0x1e, 0x23, 0x6b, 0x17, 0xfd,
	0xe7, 0xcb, 0x74, 0x9b, 0x2f, 0xe2, 0x8d, 0xd7, 0x93, 0x99, 0x01, 0xa6, 0x33, 0x03, 0x9c, 0xce,
	0x0c, 0xf0, 0x7d, 0x6e, 0x68, 0xd3, 0xb9, 0xa1, 0xfd, 0x9f, 0x1b, 0xda, 0xc7, 0x72, 0xba, 0xce,
	0xd7, 0x95, 0x4a, 0x62, 0x14, 0x52, 0xde, 0xc9, 0xcb, 0x5f, 0x48, 0xed, 0x22, 0x00, 0x00, 0xff,
	0xff, 0x19, 0x1f, 0x8b, 0x70, 0x21, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// EmissionParams Queries a list of EmissionParams items.
	EmissionParams(ctx context.Context, in *QueryEmissionParamsRequest, opts ...grpc.CallOption) (*QueryEmissionParamsResponse, error)
	// EmissionHistory Queries a list of EmissionHistory items.
	EmissionHistory(ctx context.Context, in *QueryEmissionHistoryRequest, opts ...grpc.CallOption) (*QueryEmissionHistoryResponse, error)
	// DestinationStats Queries a list of DestinationStats items.
	DestinationStats(ctx context.Context, in *QueryDestinationStatsRequest, opts ...grpc.CallOption) (*QueryDestinationStatsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.emissions.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EmissionParams(ctx context.Context, in *QueryEmissionParamsRequest, opts ...grpc.CallOption) (*QueryEmissionParamsResponse, error) {
	out := new(QueryEmissionParamsResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.emissions.v1.Query/EmissionParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EmissionHistory(ctx context.Context, in *QueryEmissionHistoryRequest, opts ...grpc.CallOption) (*QueryEmissionHistoryResponse, error) {
	out := new(QueryEmissionHistoryResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.emissions.v1.Query/EmissionHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DestinationStats(ctx context.Context, in *QueryDestinationStatsRequest, opts ...grpc.CallOption) (*QueryDestinationStatsResponse, error) {
	out := new(QueryDestinationStatsResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.emissions.v1.Query/DestinationStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// EmissionParams Queries a list of EmissionParams items.
	EmissionParams(context.Context, *QueryEmissionParamsRequest) (*QueryEmissionParamsResponse, error)
	// EmissionHistory Queries a list of EmissionHistory items.
	EmissionHistory(context.Context, *QueryEmissionHistoryRequest) (*QueryEmissionHistoryResponse, error)
	// DestinationStats Queries a list of DestinationStats items.
	DestinationStats(context.Context, *QueryDestinationStatsRequest) (*QueryDestinationStatsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) EmissionParams(ctx context.Context, req *QueryEmissionParamsRequest) (*QueryEmissionParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmissionParams not implemented")
}
func (*UnimplementedQueryServer) EmissionHistory(ctx context.Context, req *QueryEmissionHistoryRequest) (*QueryEmissionHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmissionHistory not implemented")
}
func (*UnimplementedQueryServer) DestinationStats(ctx context.Context, req *QueryDestinationStatsRequest) (*QueryDestinationStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestinationStats not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.emissions.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EmissionParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEmissionParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EmissionParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.emissions.v1.Query/EmissionParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EmissionParams(ctx, req.(*QueryEmissionParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EmissionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEmissionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EmissionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.emissions.v1.Query/EmissionHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EmissionHistory(ctx, req.(*QueryEmissionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DestinationStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDestinationStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DestinationStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.emissions.v1.Query/DestinationStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DestinationStats(ctx, req.(*QueryDestinationStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scarlettcore.emissions.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "EmissionParams",
			Handler:    _Query_EmissionParams_Handler,
		},
		{
			MethodName: "EmissionHistory",
			Handler:    _Query_EmissionHistory_Handler,
		},
		{
			MethodName: "DestinationStats",
			Handler:    _Query_DestinationStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scarlettcore/emissions/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryEmissionParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmissionParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmissionParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEmissionParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmissionParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmissionParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEmissionHistoryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmissionHistoryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmissionHistoryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEmissionHistoryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmissionHistoryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmissionHistoryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryDestinationStatsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDestinationStatsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDestinationStatsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryDestinationStatsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDestinationStatsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDestinationStatsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryEmissionParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEmissionParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEmissionHistoryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEmissionHistoryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryDestinationStatsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryDestinationStatsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmissionParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmissionParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmissionParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmissionParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmissionParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmissionParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmissionHistoryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmissionHistoryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmissionHistoryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmissionHistoryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmissionHistoryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmissionHistoryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDestinationStatsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDestinationStatsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDestinationStatsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDestinationStatsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDestinationStatsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDestinationStatsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
