// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: scarlettcore/emissions/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e8c9c209bd2763, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e8c9c209bd2763, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgUpdateEmissionSplit defines the MsgUpdateEmissionSplit message.
type MsgUpdateEmissionSplit struct {
	Creator      string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Destinations []string `protobuf:"bytes,2,rep,name=destinations,proto3" json:"destinations,omitempty"`
	Weights      []string `protobuf:"bytes,3,rep,name=weights,proto3" json:"weights,omitempty"`
	Reason       string   `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *MsgUpdateEmissionSplit) Reset()         { *m = MsgUpdateEmissionSplit{} }
func (m *MsgUpdateEmissionSplit) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateEmissionSplit) ProtoMessage()    {}
func (*MsgUpdateEmissionSplit) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e8c9c209bd2763, []int{2}
}
func (m *MsgUpdateEmissionSplit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateEmissionSplit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateEmissionSplit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateEmissionSplit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateEmissionSplit.Merge(m, src)
}
func (m *MsgUpdateEmissionSplit) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateEmissionSplit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateEmissionSplit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateEmissionSplit proto.InternalMessageInfo

func (m *MsgUpdateEmissionSplit) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateEmissionSplit) GetDestinations() []string {
	if m != nil {
		return m.Destinations
	}
	return nil
}

func (m *MsgUpdateEmissionSplit) GetWeights() []string {
	if m != nil {
		return m.Weights
	}
	return nil
}

func (m *MsgUpdateEmissionSplit) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// MsgUpdateEmissionSplitResponse defines the MsgUpdateEmissionSplitResponse message.
type MsgUpdateEmissionSplitResponse struct {
}

func (m *MsgUpdateEmissionSplitResponse) Reset()         { *m = MsgUpdateEmissionSplitResponse{} }
func (m *MsgUpdateEmissionSplitResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateEmissionSplitResponse) ProtoMessage()    {}
func (*MsgUpdateEmissionSplitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e8c9c209bd2763, []int{3}
}
func (m *MsgUpdateEmissionSplitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateEmissionSplitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateEmissionSplitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateEmissionSplitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateEmissionSplitResponse.Merge(m, src)
}
func (m *MsgUpdateEmissionSplitResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateEmissionSplitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateEmissionSplitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateEmissionSplitResponse proto.InternalMessageInfo

// MsgAddEmissionDestination defines the MsgAddEmissionDestination message.
type MsgAddEmissionDestination struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Module      string `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Weight      string `protobuf:"bytes,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Reason      string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *MsgAddEmissionDestination) Reset()         { *m = MsgAddEmissionDestination{} }
func (m *MsgAddEmissionDestination) String() string { return proto.CompactTextString(m) }
func (*MsgAddEmissionDestination) ProtoMessage()    {}
func (*MsgAddEmissionDestination) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e8c9c209bd2763, []int{4}
}
func (m *MsgAddEmissionDestination) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddEmissionDestination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddEmissionDestination.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddEmissionDestination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddEmissionDestination.Merge(m, src)
}
func (m *MsgAddEmissionDestination) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddEmissionDestination) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddEmissionDestination.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddEmissionDestination proto.InternalMessageInfo

func (m *MsgAddEmissionDestination) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAddEmissionDestination) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *MsgAddEmissionDestination) GetWeight() string {
	if m != nil {
		return m.Weight
	}
	return ""
}

func (m *MsgAddEmissionDestination) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MsgAddEmissionDestination) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// MsgAddEmissionDestinationResponse defines the MsgAddEmissionDestinationResponse message.
type MsgAddEmissionDestinationResponse struct {
}

func (m *MsgAddEmissionDestinationResponse) Reset()         { *m = MsgAddEmissionDestinationResponse{} }
func (m *MsgAddEmissionDestinationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddEmissionDestinationResponse) ProtoMessage()    {}
func (*MsgAddEmissionDestinationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e8c9c209bd2763, []int{5}
}
func (m *MsgAddEmissionDestinationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddEmissionDestinationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddEmissionDestinationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddEmissionDestinationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddEmissionDestinationResponse.Merge(m, src)
}
func (m *MsgAddEmissionDestinationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddEmissionDestinationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddEmissionDestinationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddEmissionDestinationResponse proto.InternalMessageInfo

// MsgRemoveEmissionDestination defines the MsgRemoveEmissionDestination message.
type MsgRemoveEmissionDestination struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Module  string `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Reason  string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *MsgRemoveEmissionDestination) Reset()         { *m = MsgRemoveEmissionDestination{} }
func (m *MsgRemoveEmissionDestination) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveEmissionDestination) ProtoMessage()    {}
func (*MsgRemoveEmissionDestination) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e8c9c209bd2763, []int{6}
}
func (m *MsgRemoveEmissionDestination) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveEmissionDestination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveEmissionDestination.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveEmissionDestination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveEmissionDestination.Merge(m, src)
}
func (m *MsgRemoveEmissionDestination) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveEmissionDestination) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveEmissionDestination.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveEmissionDestination proto.InternalMessageInfo

func (m *MsgRemoveEmissionDestination) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRemoveEmissionDestination) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *MsgRemoveEmissionDestination) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// MsgRemoveEmissionDestinationResponse defines the MsgRemoveEmissionDestinationResponse message.
type MsgRemoveEmissionDestinationResponse struct {
}

func (m *MsgRemoveEmissionDestinationResponse) Reset()         { *m = MsgRemoveEmissionDestinationResponse{} }
func (m *MsgRemoveEmissionDestinationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveEmissionDestinationResponse) ProtoMessage()    {}
func (*MsgRemoveEmissionDestinationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e8c9c209bd2763, []int{7}
}
func (m *MsgRemoveEmissionDestinationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveEmissionDestinationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveEmissionDestinationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveEmissionDestinationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveEmissionDestinationResponse.Merge(m, src)
}
func (m *MsgRemoveEmissionDestinationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveEmissionDestinationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveEmissionDestinationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveEmissionDestinationResponse proto.InternalMessageInfo

// MsgToggleEmissionDestination defines the MsgToggleEmissionDestination message.
type MsgToggleEmissionDestination struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Module  string `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Enabled bool   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Reason  string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *MsgToggleEmissionDestination) Reset()         { *m = MsgToggleEmissionDestination{} }
func (m *MsgToggleEmissionDestination) String() string { return proto.CompactTextString(m) }
func (*MsgToggleEmissionDestination) ProtoMessage()    {}
func (*MsgToggleEmissionDestination) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e8c9c209bd2763, []int{8}
}
func (m *MsgToggleEmissionDestination) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgToggleEmissionDestination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgToggleEmissionDestination.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgToggleEmissionDestination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgToggleEmissionDestination.Merge(m, src)
}
func (m *MsgToggleEmissionDestination) XXX_Size() int {
	return m.Size()
}
func (m *MsgToggleEmissionDestination) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgToggleEmissionDestination.DiscardUnknown(m)
}

var xxx_messageInfo_MsgToggleEmissionDestination proto.InternalMessageInfo

func (m *MsgToggleEmissionDestination) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgToggleEmissionDestination) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *MsgToggleEmissionDestination) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *MsgToggleEmissionDestination) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// MsgToggleEmissionDestinationResponse defines the MsgToggleEmissionDestinationResponse message.
type MsgToggleEmissionDestinationResponse struct {
}

func (m *MsgToggleEmissionDestinationResponse) Reset()         { *m = MsgToggleEmissionDestinationResponse{} }
func (m *MsgToggleEmissionDestinationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgToggleEmissionDestinationResponse) ProtoMessage()    {}
func (*MsgToggleEmissionDestinationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e8c9c209bd2763, []int{9}
}
func (m *MsgToggleEmissionDestinationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgToggleEmissionDestinationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgToggleEmissionDestinationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgToggleEmissionDestinationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgToggleEmissionDestinationResponse.Merge(m, src)
}
func (m *MsgToggleEmissionDestinationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgToggleEmissionDestinationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgToggleEmissionDestinationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgToggleEmissionDestinationResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "scarlettcore.emissions.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "scarlettcore.emissions.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgUpdateEmissionSplit)(nil), "scarlettcore.emissions.v1.MsgUpdateEmissionSplit")
	proto.RegisterType((*MsgUpdateEmissionSplitResponse)(nil), "scarlettcore.emissions.v1.MsgUpdateEmissionSplitResponse")
	proto.RegisterType((*MsgAddEmissionDestination)(nil), "scarlettcore.emissions.v1.MsgAddEmissionDestination")
	proto.RegisterType((*MsgAddEmissionDestinationResponse)(nil), "scarlettcore.emissions.v1.MsgAddEmissionDestinationResponse")
	proto.RegisterType((*MsgRemoveEmissionDestination)(nil), "scarlettcore.emissions.v1.MsgRemoveEmissionDestination")
	proto.RegisterType((*MsgRemoveEmissionDestinationResponse)(nil), "scarlettcore.emissions.v1.MsgRemoveEmissionDestinationResponse")
	proto.RegisterType((*MsgToggleEmissionDestination)(nil), "scarlettcore.emissions.v1.MsgToggleEmissionDestination")
	proto.RegisterType((*MsgToggleEmissionDestinationResponse)(nil), "scarlettcore.emissions.v1.MsgToggleEmissionDestinationResponse")
}

func init() {
	proto.RegisterFile("scarlettcore/emissions/v1/tx.proto", fileDescriptor_02e8c9c209bd2763)
}

var fileDescriptor_02e8c9c209bd2763 = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0x4f, 0x6b, 0x13, 0x4f,
	0x18, 0xc7, 0x33, 0xcd, 0xaf, 0xe9, 0x2f, 0x4f, 0x03, 0xe2, 0x5a, 0xd2, 0xcd, 0x22, 0xdb, 0x74,
	0x95, 0x12, 0x02, 0xcd, 0x92, 0x28, 0x4a, 0xab, 0x20, 0x0d, 0xf5, 0x18, 0x90, 0xad, 0x5e, 0xbc,
	0xc8, 0x36, 0x3b, 0x4c, 0x17, 0xb2, 0x3b, 0xcb, 0xce, 0x34, 0xb6, 0x37, 0xd1, 0x9b, 0x78, 0xe8,
	0xc5, 0xf7, 0x20, 0x9e, 0x72, 0xf0, 0x0d, 0x78, 0xb2, 0x07, 0x0f, 0xc5, 0x93, 0x27, 0x91, 0xe4,
	0x90, 0xb7, 0x21, 0xfb, 0x37, 0x7f, 0xcc, 0x6e, 0x62, 0x40, 0x2f, 0x21, 0xcf, 0x9f, 0xef, 0xf3,
	0x7c, 0xbe, 0x64, 0x26, 0x03, 0x0a, 0x6b, 0xeb, 0x6e, 0x07, 0x73, 0xde, 0xa6, 0x2e, 0x56, 0xb1,
	0x65, 0x32, 0x66, 0x52, 0x9b, 0xa9, 0xdd, 0xba, 0xca, 0xcf, 0x6a, 0x8e, 0x4b, 0x39, 0x15, 0x4a,
	0xe3, 0x3d, 0xb5, 0xb8, 0xa7, 0xd6, 0xad, 0x4b, 0xd7, 0x75, 0xcb, 0xb4, 0xa9, 0xea, 0x7f, 0x06,
	0xdd, 0xd2, 0x66, 0x9b, 0x32, 0x8b, 0x32, 0xd5, 0x62, 0xc4, 0x9b, 0x62, 0x31, 0x12, 0x16, 0x4a,
	0x41, 0xe1, 0x85, 0x1f, 0xa9, 0x41, 0x10, 0x96, 0x36, 0x08, 0x25, 0x34, 0xc8, 0x7b, 0xdf, 0xc2,
	0xec, 0x4e, 0x32, 0x9b, 0xa3, 0xbb, 0xba, 0x15, 0xaa, 0x95, 0xaf, 0x08, 0xae, 0xb5, 0x18, 0x79,
	0xe6, 0x18, 0x3a, 0xc7, 0x4f, 0xfc, 0x8a, 0x70, 0x0f, 0xf2, 0xfa, 0x29, 0x3f, 0xa1, 0xae, 0xc9,
	0xcf, 0x45, 0x54, 0x46, 0x95, 0x7c, 0x53, 0xfc, 0xf6, 0x69, 0x77, 0x23, 0x5c, 0x7b, 0x60, 0x18,
	0x2e, 0x66, 0xec, 0x88, 0xbb, 0xa6, 0x4d, 0xb4, 0x51, 0xab, 0x70, 0x08, 0xb9, 0x60, 0xb6, 0xb8,
	0x52, 0x46, 0x95, 0xf5, 0xc6, 0x76, 0x2d, 0xd1, 0x7c, 0x2d, 0x58, 0xd5, 0xcc, 0x5f, 0xfe, 0xd8,
	0xca, 0x7c, 0x18, 0xf6, 0xaa, 0x48, 0x0b, 0xb5, 0xfb, 0x0f, 0x5e, 0x0f, 0x7b, 0xd5, 0xd1, 0xd4,
	0xb7, 0xc3, 0x5e, 0xb5, 0x32, 0x61, 0xe6, 0x6c, 0xcc, 0xce, 0x14, 0xba, 0x52, 0x82, 0xcd, 0xa9,
	0x94, 0x86, 0x99, 0x43, 0x6d, 0x86, 0x95, 0x1e, 0x82, 0x62, 0x5c, 0x7b, 0x1c, 0x4e, 0x38, 0x72,
	0x3a, 0x26, 0x17, 0x1a, 0xb0, 0xd6, 0x76, 0xb1, 0xce, 0xa9, 0x3b, 0xd7, 0x6e, 0xd4, 0x28, 0x28,
	0x50, 0x30, 0x30, 0xe3, 0xa6, 0xad, 0x73, 0x8f, 0x44, 0x5c, 0x29, 0x67, 0x2b, 0x79, 0x6d, 0x22,
	0x27, 0x88, 0xb0, 0xf6, 0x12, 0x9b, 0xe4, 0x84, 0x33, 0x31, 0xeb, 0x97, 0xa3, 0x50, 0x28, 0x42,
	0xce, 0xc5, 0x3a, 0xa3, 0xb6, 0xf8, 0x9f, 0xb7, 0x50, 0x0b, 0xa3, 0xfd, 0x82, 0x67, 0x3e, 0xda,
	0xa1, 0x94, 0x41, 0x9e, 0x4d, 0x1c, 0x9b, 0xfa, 0x82, 0xa0, 0xd4, 0x62, 0xe4, 0xc0, 0x30, 0xa2,
	0xfa, 0xe1, 0x08, 0x60, 0x29, 0x5f, 0x45, 0xc8, 0x59, 0xd4, 0x38, 0xed, 0x60, 0xff, 0x47, 0xcc,
	0x6b, 0x61, 0xe4, 0xe5, 0x03, 0x78, 0x31, 0x1b, 0xe4, 0x83, 0x48, 0x28, 0xc3, 0xba, 0x81, 0x59,
	0xdb, 0x35, 0x1d, 0x6f, 0x65, 0x68, 0x67, 0x3c, 0x35, 0xe6, 0x75, 0x35, 0xc5, 0xeb, 0x2d, 0xd8,
	0x4e, 0x34, 0x12, 0xdb, 0xbd, 0x40, 0x70, 0xb3, 0xc5, 0x88, 0x86, 0x2d, 0xda, 0xc5, 0xff, 0xc0,
	0x71, 0xc8, 0x9d, 0x4d, 0xe1, 0xde, 0x81, 0xdb, 0x69, 0x44, 0x31, 0xfa, 0xc7, 0x00, 0xfd, 0x29,
	0x25, 0xa4, 0xf3, 0xd7, 0xd1, 0x45, 0x58, 0xc3, 0xb6, 0x7e, 0xdc, 0xc1, 0x86, 0xcf, 0xfe, 0xbf,
	0x16, 0x85, 0x0b, 0x1e, 0xbc, 0xc0, 0x54, 0x22, 0x6b, 0x64, 0xaa, 0xf1, 0x79, 0x15, 0xb2, 0x2d,
	0x46, 0x04, 0x1b, 0x0a, 0x13, 0xff, 0x20, 0xd5, 0x94, 0x9b, 0x3f, 0x75, 0x3f, 0xa5, 0xc6, 0xe2,
	0xbd, 0xd1, 0x5e, 0xe1, 0x0d, 0x82, 0x1b, 0xb3, 0x2e, 0x72, 0x7d, 0x91, 0x59, 0x13, 0x12, 0x69,
	0xef, 0x8f, 0x25, 0x31, 0xc5, 0x3b, 0x04, 0xc5, 0x84, 0x9b, 0x77, 0x37, 0x7d, 0xea, 0x6c, 0x95,
	0xf4, 0x70, 0x19, 0x55, 0x8c, 0xf3, 0x1e, 0x41, 0x29, 0xf9, 0x66, 0xdc, 0x4f, 0x9f, 0x9d, 0x28,
	0x94, 0x1e, 0x2d, 0x29, 0x9c, 0xe0, 0x4a, 0x3e, 0xf6, 0x73, 0xb8, 0x12, 0x85, 0xf3, 0xb8, 0xe6,
	0x1e, 0x5e, 0x69, 0xf5, 0x95, 0xf7, 0xee, 0x34, 0xf7, 0x2e, 0xfb, 0x32, 0xba, 0xea, 0xcb, 0xe8,
	0x67, 0x5f, 0x46, 0x17, 0x03, 0x39, 0x73, 0x35, 0x90, 0x33, 0xdf, 0x07, 0x72, 0xe6, 0xf9, 0x56,
	0xb4, 0x60, 0xf7, 0xb7, 0x77, 0x87, 0x9f, 0x3b, 0x98, 0x1d, 0xe7, 0xfc, 0x37, 0xf4, 0xce, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xf6, 0x14, 0x9d, 0x09, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// UpdateEmissionSplit defines the UpdateEmissionSplit RPC.
	UpdateEmissionSplit(ctx context.Context, in *MsgUpdateEmissionSplit, opts ...grpc.CallOption) (*MsgUpdateEmissionSplitResponse, error)
	// AddEmissionDestination defines the AddEmissionDestination RPC.
	AddEmissionDestination(ctx context.Context, in *MsgAddEmissionDestination, opts ...grpc.CallOption) (*MsgAddEmissionDestinationResponse, error)
	// RemoveEmissionDestination defines the RemoveEmissionDestination RPC.
	RemoveEmissionDestination(ctx context.Context, in *MsgRemoveEmissionDestination, opts ...grpc.CallOption) (*MsgRemoveEmissionDestinationResponse, error)
	// ToggleEmissionDestination defines the ToggleEmissionDestination RPC.
	ToggleEmissionDestination(ctx context.Context, in *MsgToggleEmissionDestination, opts ...grpc.CallOption) (*MsgToggleEmissionDestinationResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.emissions.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateEmissionSplit(ctx context.Context, in *MsgUpdateEmissionSplit, opts ...grpc.CallOption) (*MsgUpdateEmissionSplitResponse, error) {
	out := new(MsgUpdateEmissionSplitResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.emissions.v1.Msg/UpdateEmissionSplit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddEmissionDestination(ctx context.Context, in *MsgAddEmissionDestination, opts ...grpc.CallOption) (*MsgAddEmissionDestinationResponse, error) {
	out := new(MsgAddEmissionDestinationResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.emissions.v1.Msg/AddEmissionDestination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveEmissionDestination(ctx context.Context, in *MsgRemoveEmissionDestination, opts ...grpc.CallOption) (*MsgRemoveEmissionDestinationResponse, error) {
	out := new(MsgRemoveEmissionDestinationResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.emissions.v1.Msg/RemoveEmissionDestination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ToggleEmissionDestination(ctx context.Context, in *MsgToggleEmissionDestination, opts ...grpc.CallOption) (*MsgToggleEmissionDestinationResponse, error) {
	out := new(MsgToggleEmissionDestinationResponse)
	err := c.cc.Invoke(ctx, "/scarlettcore.emissions.v1.Msg/ToggleEmissionDestination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// UpdateEmissionSplit defines the UpdateEmissionSplit RPC.
	UpdateEmissionSplit(context.Context, *MsgUpdateEmissionSplit) (*MsgUpdateEmissionSplitResponse, error)
	// AddEmissionDestination defines the AddEmissionDestination RPC.
	AddEmissionDestination(context.Context, *MsgAddEmissionDestination) (*MsgAddEmissionDestinationResponse, error)
	// RemoveEmissionDestination defines the RemoveEmissionDestination RPC.
	RemoveEmissionDestination(context.Context, *MsgRemoveEmissionDestination) (*MsgRemoveEmissionDestinationResponse, error)
	// ToggleEmissionDestination defines the ToggleEmissionDestination RPC.
	ToggleEmissionDestination(context.Context, *MsgToggleEmissionDestination) (*MsgToggleEmissionDestinationResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) UpdateEmissionSplit(ctx context.Context, req *MsgUpdateEmissionSplit) (*MsgUpdateEmissionSplitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmissionSplit not implemented")
}
func (*UnimplementedMsgServer) AddEmissionDestination(ctx context.Context, req *MsgAddEmissionDestination) (*MsgAddEmissionDestinationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEmissionDestination not implemented")
}
func (*UnimplementedMsgServer) RemoveEmissionDestination(ctx context.Context, req *MsgRemoveEmissionDestination) (*MsgRemoveEmissionDestinationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveEmissionDestination not implemented")
}
func (*UnimplementedMsgServer) ToggleEmissionDestination(ctx context.Context, req *MsgToggleEmissionDestination) (*MsgToggleEmissionDestinationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleEmissionDestination not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.emissions.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateEmissionSplit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateEmissionSplit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateEmissionSplit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.emissions.v1.Msg/UpdateEmissionSplit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateEmissionSplit(ctx, req.(*MsgUpdateEmissionSplit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddEmissionDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddEmissionDestination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddEmissionDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.emissions.v1.Msg/AddEmissionDestination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddEmissionDestination(ctx, req.(*MsgAddEmissionDestination))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveEmissionDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveEmissionDestination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveEmissionDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.emissions.v1.Msg/RemoveEmissionDestination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveEmissionDestination(ctx, req.(*MsgRemoveEmissionDestination))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ToggleEmissionDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgToggleEmissionDestination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ToggleEmissionDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scarlettcore.emissions.v1.Msg/ToggleEmissionDestination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ToggleEmissionDestination(ctx, req.(*MsgToggleEmissionDestination))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scarlettcore.emissions.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "UpdateEmissionSplit",
			Handler:    _Msg_UpdateEmissionSplit_Handler,
		},
		{
			MethodName: "AddEmissionDestination",
			Handler:    _Msg_AddEmissionDestination_Handler,
		},
		{
			MethodName: "RemoveEmissionDestination",
			Handler:    _Msg_RemoveEmissionDestination_Handler,
		},
		{
			MethodName: "ToggleEmissionDestination",
			Handler:    _Msg_ToggleEmissionDestination_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scarlettcore/emissions/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateEmissionSplit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateEmissionSplit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateEmissionSplit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Weights) > 0 {
		for iNdEx := len(m.Weights) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Weights[iNdEx])
			copy(dAtA[i:], m.Weights[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Weights[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Destinations) > 0 {
		for iNdEx := len(m.Destinations) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Destinations[iNdEx])
			copy(dAtA[i:], m.Destinations[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Destinations[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateEmissionSplitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateEmissionSplitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateEmissionSplitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddEmissionDestination) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddEmissionDestination) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddEmissionDestination) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Weight) > 0 {
		i -= len(m.Weight)
		copy(dAtA[i:], m.Weight)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Weight)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddEmissionDestinationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddEmissionDestinationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddEmissionDestinationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRemoveEmissionDestination) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveEmissionDestination) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveEmissionDestination) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveEmissionDestinationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveEmissionDestinationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveEmissionDestinationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgToggleEmissionDestination) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgToggleEmissionDestination) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgToggleEmissionDestination) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x22
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgToggleEmissionDestinationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgToggleEmissionDestinationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgToggleEmissionDestinationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateEmissionSplit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Destinations) > 0 {
		for _, s := range m.Destinations {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.Weights) > 0 {
		for _, s := range m.Weights {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateEmissionSplitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddEmissionDestination) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Weight)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddEmissionDestinationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRemoveEmissionDestination) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRemoveEmissionDestinationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgToggleEmissionDestination) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgToggleEmissionDestinationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateEmissionSplit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateEmissionSplit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateEmissionSplit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destinations", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Destinations = append(m.Destinations, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weights", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Weights = append(m.Weights, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateEmissionSplitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateEmissionSplitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateEmissionSplitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddEmissionDestination) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddEmissionDestination: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddEmissionDestination: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Weight = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddEmissionDestinationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddEmissionDestinationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddEmissionDestinationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveEmissionDestination) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveEmissionDestination: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveEmissionDestination: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveEmissionDestinationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveEmissionDestinationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveEmissionDestinationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgToggleEmissionDestination) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgToggleEmissionDestination: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgToggleEmissionDestination: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgToggleEmissionDestinationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgToggleEmissionDestinationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgToggleEmissionDestinationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
